In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
import re
import joblib
import string

In [2]:
fake = pd.read_csv('Fake.csv')
true = pd.read_csv('True.csv')

In [3]:
fake.head()

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"

In [4]:
true.head()

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"

In [5]:
fake['class'] = 0
true['class'] = 1

In [6]:
data = pd.concat([fake,true],axis=0)

In [7]:
data.sample(10)

,title,text,subject,date,class
19708,China says North Korea nuclear issue must be r...,BEIJING (Reuters) - The North Korean nuclear i...,worldnews,"September 19, 2017",1
136,Trump Went To Japan And Immediately Proved He...,Who knew that Donald Trump would humiliate him...,News,"November 5, 2017",0
12278,"Russia's Putin, on track for easy re-election,...",MOSCOW (Reuters) - Russian President Vladimir ...,worldnews,"December 14, 2017",1
19880,FLORIDA DOCTOR Under Fire After Running TV Ad ...,"As a woman, I have to say I agree with this do...",left-news,"Oct 3, 2016",0
21015,"Disabled in war, Afghan soldiers seek a living...","JALALABAD, Afghanistan (Reuters) - Afghan sold...",worldnews,"September 5, 2017",1
18701,WATCH TUCKER CARLSON’S Heated Debate With Delu...,"Tucker Carlson interviews Jose Antonio Vargas,...",left-news,"May 3, 2017",0
11733,Russian Foreign Ministry says latest U.S. sanc...,MOSCOW (Reuters) - The latest U.S. sanctions i...,worldnews,"December 21, 2017",1
15886,APPLE’S CEO SAYS RELIGIOUS FREEDOM LAWS ARE ‘D...,The gay mafia has a new corporate Don. This i...,politics,"Mar 31, 2015",0
1846,Sean Penn TORE Steve Bannon To RIBBONS After ...,"Sean Penn is not exactly one to mince words, a...",News,"April 9, 2017",0
23460,Trial By YouTube: Mainstream Media Use Second-...,Patrick Henningsen 21st Century WireThere exi...,Middle-east,"January 28, 2016",0

In [8]:
data = data.drop(["title","subject","date"] , axis = 1)

In [9]:
data.reset_index(inplace=True)

In [10]:
data.sample(10)

       index                                               text  class
41545  18064  MEXICO CITY (Reuters) - An indigenous woman ba...      1
6331    6331  Finding out Donald Trump was his own publicist...      0
9237    9237  On September 5, 2017, the Daily Mail reported:...      0
25315   1834  WASHINGTON (Reuters) - U.S. President Donald T...      1
40187  16706  LANY, Czech Republic (Reuters) - Czech billion...      1
6800    6800  Fox News loves Wisconsin s Sheriff David Clark...      0
383      383  Martin Shkreli quickly gained notoriety during...      0
42898  19417  NEW YORK (Reuters) - U.S. Ambassador to the Un...      1
26685   3204  WASHINGTON (Reuters) - U.S. Secretary of State...      1
36908  13427  ROME (Reuters) - U.S. President Donald Trump s...      1

In [11]:
data.drop(['index'],axis =1 , inplace=True)

In [12]:
data.sample(5)

                                                    text  class
33658  WASHINGTON (Reuters) - Senior U.S. and German ...      1
43358  SINGAPORE (Reuters) - Hundreds of Singaporeans...      1
12323   There is Nothing Un-American About Reparation...      0
34355  WASHINGTON (Reuters) - The U.S. Senate voted u...      1
39189  DHAKA (Reuters) - The U.S. government will con...      1

In [13]:
import re
import string

def clean_text(text):
    text = text.lower()  # Convert to lowercase
    text = re.sub(r'\[.*?\]', '', text)  # Remove text inside square brackets
    text = re.sub(r'http\S+|www\.\S+', '', text)  # Remove URLs
    text = re.sub(r'<.*?>', '', text)  # Remove HTML tags
    text = re.sub(r'[%s]' % re.escape(string.punctuation), '', text)  # Remove punctuation
    text = re.sub(r'\n', '', text)  # Remove newlines
    text = re.sub(r'\w*\d\w*', '', text)  # Remove words containing numbers
    return text

In [14]:
data["text"] = data["text"].apply(clean_text)

In [15]:
x=data["text"]
y=data["class"]

xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.25,random_state=42)

In [16]:
vectorizer = TfidfVectorizer()
xv_train = vectorizer.fit_transform(xtrain)
xv_test = vectorizer.transform(xtest)

In [17]:
lr =LogisticRegression()
lr.fit(xv_train,ytrain)

LogisticRegression()

In [18]:
prediction = lr.predict(xv_test)